version: '3'
services:
  app:
    build: .
    environment:
      NODE_ENV: development
      NODE_APP_INSTANCE: ''
    ports:
      - '8080:8080'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  nginx:
    image: nginx:1.14
    links:
      - app
    ports:
      - '80:80'
    volumes:
- ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro